apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: argo-logs-truncation-bug-repro-
spec:
  entrypoint: reproduce-bug
  templates:
  - name: reproduce-bug
    container:
      image: thundergolfer/argo-logs-truncation-bug-repro:45c8bdab
